name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/1600822305/AetherLink.git
          git fetch upstream --tags

      - name: Sync main branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git reset --hard upstream/main
          git fetch upstream --tags
          git push origin --tags

      - name: Push main branch
        run: |
          git push origin main
